push to ECR

diff --git a/.github/workflows/axisbank.yml b/.github/workflows/axisbank.yml
--- a/.github/workflows/axisbank.yml
+++ b/.github/workflows/axisbank.yml
@@ -1,135 +1,135 @@
-name: Deploying Java Trail Application into the Ec2
+# name: Deploying Java Trail Application into the Ec2
 
-on:
-    push:
-        branches: ["main"]
+# on:
+#     push:
+#         branches: ["main"]
 
-jobs:
-    build:
-        runs-on: ubuntu-latest
+# jobs:
+#     build:
+#         runs-on: ubuntu-latest
 
-        steps:
+#         steps:
 
-            - name: checkout code
-              uses: actions/checkout@v4
+#             - name: checkout code
+#               uses: actions/checkout@v4
 
-            - name: Setup java
-              uses: actions/setup-java@v4
-              with: 
-                java-version: '17'
-                distribution: 'temurin'
+#             - name: Setup java
+#               uses: actions/setup-java@v4
+#               with: 
+#                 java-version: '17'
+#                 distribution: 'temurin'
 
-            # - name: Build and test
-            #   working-directory: axisbank
-            #   run: mvn clean test
+#             # - name: Build and test
+#             #   working-directory: axisbank
+#             #   run: mvn clean test
 
-            - name: Build Code
-              working-directory: axisbank
-              run: mvn clean package
+#             - name: Build Code
+#               working-directory: axisbank
+#               run: mvn clean package
 
-            - name: Check target folder
-              working-directory: axisbank
-              run: ls target
+#             - name: Check target folder
+#               working-directory: axisbank
+#               run: ls target
 
-            - name: Build Image into Docker
-              working-directory: axisbank
-              run: docker build -t axisbank-app:${GITHUB_RUN_NUMBER} .  #-f axisbank/Dockerfile axisbank
+#             - name: Build Image into Docker
+#               working-directory: axisbank
+#               run: docker build -t axisbank-app:${GITHUB_RUN_NUMBER} .  #-f axisbank/Dockerfile axisbank
       
-            - name: Check image file
-              run: docker image ls
+#             - name: Check image file
+#               run: docker image ls
       
-            - name: Docker Login
-              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+#             - name: Docker Login
+#               run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
       
-            - name: Tag name
-              run: docker tag axisbank-app:${{ github.run_number }} rohitkumar4praja/axisbank-app:${{ github.run_number }}
+#             - name: Tag name
+#               run: docker tag axisbank-app:${{ github.run_number }} rohitkumar4praja/axisbank-app:${{ github.run_number }}
       
-            - name: push Image
-              run: docker push rohitkumar4praja/axisbank-app:${{ github.run_number }}
+#             - name: push Image
+#               run: docker push rohitkumar4praja/axisbank-app:${{ github.run_number }}
 
-#################################################################################
-##---------------Deploy to Ec2 Server------------------------------------------
-            - name: Deploy to EC2
-              uses: appleboy/ssh-action@v1.0.3
-              with:
-                host: ${{ secrets.EC2_HOST }}
-                username: ${{ secrets.EC2_USER }}
-                key: ${{ secrets.EC2_KEY }}
-                script: |
-                  set -e
+# #################################################################################
+# ##---------------Deploy to Ec2 Server------------------------------------------
+#             - name: Deploy to EC2
+#               uses: appleboy/ssh-action@v1.0.3
+#               with:
+#                 host: ${{ secrets.EC2_HOST }}
+#                 username: ${{ secrets.EC2_USER }}
+#                 key: ${{ secrets.EC2_KEY }}
+#                 script: |
+#                   set -e
 
-                  APP_NAME="axisbank"
-                  NEW_IMAGE="rohitkumar4praja/axisbank-app:${{ github.run_number }}"
-                  PREV_FILE="$HOME/prev_image.txt"
+#                   APP_NAME="axisbank"
+#                   NEW_IMAGE="rohitkumar4praja/axisbank-app:${{ github.run_number }}"
+#                   PREV_FILE="$HOME/prev_image.txt"
 
-                  echo "Step 1: Save current running image"
-                  CURRENT_IMAGE=$(docker inspect --format='{{.Config.Image}}' $APP_NAME 2>/dev/null || echo "")
+#                   echo "Step 1: Save current running image"
+#                   CURRENT_IMAGE=$(docker inspect --format='{{.Config.Image}}' $APP_NAME 2>/dev/null || echo "")
 
-                  if [ ! -z "$CURRENT_IMAGE" ]; then
-                    echo "$CURRENT_IMAGE" > $PREV_FILE
-                    echo "Saved previous image: $CURRENT_IMAGE"
-                  else
-                    echo "No previous container found"
-                  fi
+#                   if [ ! -z "$CURRENT_IMAGE" ]; then
+#                     echo "$CURRENT_IMAGE" > $PREV_FILE
+#                     echo "Saved previous image: $CURRENT_IMAGE"
+#                   else
+#                     echo "No previous container found"
+#                   fi
 
 
-                  echo "Step 2: Deploy new image"
+#                   echo "Step 2: Deploy new image"
 
-                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-                  docker pull $NEW_IMAGE
-                  docker stop $APP_NAME || true
-                  docker rm $APP_NAME || true
-                  docker run -d -p 8080:8080 --name $APP_NAME $NEW_IMAGE
+#                   echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+#                   docker pull $NEW_IMAGE
+#                   docker stop $APP_NAME || true
+#                   docker rm $APP_NAME || true
+#                   docker run -d -p 8080:8080 --name $APP_NAME $NEW_IMAGE
 
-                  echo "Step 3: Health check"
-                  SUCCESS=false
+#                   echo "Step 3: Health check"
+#                   SUCCESS=false
 
-                  # for i in {1..5}; do
-                  #   if curl -f http://localhost:8080/health; then
-                  #     SUCCESS=true
-                  #     break
-                  #   fi
-                  #   echo "Retry $i..."
-                  #   sleep 5
-                  # done
-                  PASS_COUNT=0
+#                   # for i in {1..5}; do
+#                   #   if curl -f http://localhost:8080/health; then
+#                   #     SUCCESS=true
+#                   #     break
+#                   #   fi
+#                   #   echo "Retry $i..."
+#                   #   sleep 5
+#                   # done
+#                   PASS_COUNT=0
 
-                  for i in {1..6}; do
-                    echo "Health check attempt $i..."
+#                   for i in {1..6}; do
+#                     echo "Health check attempt $i..."
 
-                    if curl -f http://localhost:8080/health; then
-                      PASS_COUNT=$((PASS_COUNT + 1))
-                    else
-                      PASS_COUNT=0
-                    fi
+#                     if curl -f http://localhost:8080/health; then
+#                       PASS_COUNT=$((PASS_COUNT + 1))
+#                     else
+#                       PASS_COUNT=0
+#                     fi
 
-                    # require 3 consecutive successes
-                    if [ $PASS_COUNT -ge 3 ]; then
-                      SUCCESS=true
-                      break
-                    fi
+#                     # require 3 consecutive successes
+#                     if [ $PASS_COUNT -ge 3 ]; then
+#                       SUCCESS=true
+#                       break
+#                     fi
 
-                    sleep 5
-                  done
+#                     sleep 5
+#                   done
 
-                  echo "Step 4: Result"
+#                   echo "Step 4: Result"
 
-                  if [ "$SUCCESS" = true ]; then
-                    echo "Deployment successful"
-                  else
-                    echo "Deployment failed. Rolling back..."
+#                   if [ "$SUCCESS" = true ]; then
+#                     echo "Deployment successful"
+#                   else
+#                     echo "Deployment failed. Rolling back..."
 
-                    docker stop $APP_NAME || true
-                    docker rm $APP_NAME || true
+#                     docker stop $APP_NAME || true
+#                     docker rm $APP_NAME || true
 
-                    if [ -f "$PREV_FILE" ]; then
-                      PREV_IMAGE=$(cat $PREV_FILE)
-                      echo "Restoring: $PREV_IMAGE"
-                      docker run -d -p 8080:8080 --name $APP_NAME $PREV_IMAGE
-                    else
-                      echo "No previous image found!"
-                      exit 1
-                    fi
-                  fi
+#                     if [ -f "$PREV_FILE" ]; then
+#                       PREV_IMAGE=$(cat $PREV_FILE)
+#                       echo "Restoring: $PREV_IMAGE"
+#                       docker run -d -p 8080:8080 --name $APP_NAME $PREV_IMAGE
+#                     else
+#                       echo "No previous image found!"
+#                       exit 1
+#                     fi
+#                   fi
 
 
